travis:
  secure:
    BINSTAR_TOKEN: hAdisERLVGWwFYkz2wPOpBpOM0ENPsGqSCeRuW14WKsH6cr6Q1XMYKaQCftsAiD/482rtp6mwNvLIYltlRzyYXvGbEx8NAIPFm1842lmC9pbdWrr5NXLSc/+U5dgjSdNGZgac4vSboPfUBIGo6bb/UpJxsuq1rjjb62XtujwQXd+ytSVSsgdEmErrNsNBfyASRminuviJrXefr/R7NmmYmAuS+Gux01zMO9bzjwFQEjUCopYdurttDyM90rV+psJppABRMw2kXX0hWYkV4JLqlHeFSv0IrbGlkz57fsgKATlSFD3B45IWgkijZOSS99w1yIu90Lji8H2/kCsdokTZxgBzd06gJTDzd9tT1oKToHUlhzX5fk87zK9GVf9/Odw8gPS4hfh1yf+M+H4DMcjp0IUdNLl1DnLOcemeElub2Fd+wKlgUBo0TlzxVGIjU+dDk3NpOdgdsIWAspXisGcFALf//VrgD313gAZJ5Qf6zy18N1UU69+s5PDMhwOEMY+W2jGqOimgsdOUaj2bPgkqNsHbMGrS3szUd9IaaCIpgB5bet/sO1qRQ+3QS6M+3q5V8pDexskTzbLaBL8KEEOhbOxHxMzA+GTmsnxntHSXhNdb1/ILT/2uCvx1DUW76LgEn5RlOwAOe3FlIyUtqpDMbOH8pTQAoHJZ5R1jY/YmyE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
